name: Build IPK

on:
  workflow_dispatch:  # 👈 Cái này cho phép bạn chạy thủ công từ tab "Actions"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm dpkg-dev coreutils
          sudo npm install -g ares-cli

      - name: Build IPK
        run: |
          make clean || true
          make

      - name: Upload built IPK
        uses: actions/upload-artifact@v4
        with:
          name: downgr8-ipk
          path: lol.downgr8_0.0.1_all.ipk
